Controllers/DatosReclutamientoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using RecursosHumanos.Models;
using RecursosHumanos.Models.ViewModels.Reclutamiento;
using ClosedXML.Excel;
using System.IO;


namespace RecursosHumanos.Controllers
{
    public class DatosReclutamientoesController : Controller
    {
        private readonly ApplicationDbContext _context;

        #region builder

        public DatosReclutamientoesController(ApplicationDbContext context)
        {
            _context = context;
        }
        #endregion


        #region Index
        // GET: DatosReclutamientoes
        [Authorize]
        public async Task<IActionResult> Index(ReclutamientoIndexVM filtro,int pagina=1)
        {
            int pageSize = 10;

            var query = BuildQuery(filtro);

            int totalRegistros = await query.CountAsync();

            var datos = await query
                .Skip((pagina - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            // Cargar combos con primer elemento en blanco
            var empresas = _context.Empresas
                .Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Empresa1 })
                .ToList();
            empresas.Insert(0, new SelectListItem { Value = "", Text = "" });

            var bases = _context.Bases
                .Select(b => new SelectListItem { Value = b.Id.ToString(), Text = b.Base1 })
                .ToList();
            bases.Insert(0, new SelectListItem { Value = "", Text = "" });

            var fuentes = _context.Fuentes
                .Select(f => new SelectListItem { Value = f.Id.ToString(), Text = f.Fuente1 })
                .ToList();
            fuentes.Insert(0, new SelectListItem { Value = "", Text = "" });

            var estatus = _context.Estatuses
                .Select(e => new SelectListItem { Value = e.Id.ToString(), Text = e.Estatus1 })
                .ToList();
            estatus.Insert(0, new SelectListItem { Value = "", Text = "" });

            var posiciones = _context.Posicions
                .Select(p => new SelectListItem { Value = p.Id.ToString(), Text = p.Posicion1 })
                .ToList();
            posiciones.Insert(0, new SelectListItem { Value = "", Text = "" });

            var sexos = _context.Sexos
                .Select(s => new SelectListItem { Value = s.Id.ToString(), Text = s.Sexo1 })
                .ToList();
            sexos.Insert(0, new SelectListItem { Value = "", Text = "" });

            var reclutadores = _context.Reclutadors
                .Select(r => new SelectListItem { Value = r.Id.ToString(), Text = r.NombreCompleto })
                .ToList();
            reclutadores.Insert(0, new SelectListItem { Value = "", Text = "" });

            var model = new ReclutamientoIndexVM
            {
                Datos = datos,
                Nuevo = new DatosReclutamiento(),

                Nombre = filtro.Nombre,
                Telefono = filtro.Telefono,
                FechaDesde = filtro.FechaDesde,
                FechaHasta = filtro.FechaHasta,
                IdReclutador = filtro.IdReclutador,

                Empresas = empresas,
                Bases = bases,
                Fuentes = fuentes,
                Estatus = estatus,
                Posiciones = posiciones,
                Sexos = sexos,
                Reclutadores = reclutadores,
                PaginaActual = pagina,
                TotalPaginas = (int)Math.Ceiling(totalRegistros / (double)pageSize)
            };

            return View(model);
        }

        #endregion


        #region Detalles
        // GET: DatosReclutamientoes/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var datosReclutamiento = await _context.DatosReclutamientos
                .Include(d => d.IdBaseNavigation)
                .Include(d => d.IdEmpresaNavigation)
                .Include(d => d.IdEstatusNavigation)
                .Include(d => d.IdFuenteNavigation)
                .Include(d => d.IdPosicionNavigation)
                .Include(d => d.IdReclutadorNavigation)
                .Include(d => d.IdSexoNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (datosReclutamiento == null)
            {
                return NotFound();
            }

            return View(datosReclutamiento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind(Prefix = "Nuevo")] DatosReclutamiento nuevo)
        {
            if (!ModelState.IsValid)
            {
                // Recargar los combos si es que vas a regresar a la vista
                ReclutamientoIndexVM vm = new ReclutamientoIndexVM
                {
                    Nuevo = nuevo,
                    MostrarModal=true,
                    Empresas = _context.Empresas.Select(e => new SelectListItem
                    {
                        Value = e.Id.ToString(),
                        Text = e.Empresa1
                    }).ToList(),

                 
                    Bases = _context.Bases.Select(b => new SelectListItem
                    {
                        Value = b.Id.ToString(),
                        Text = b.Base1
                    }).ToList(),
                    Fuentes = _context.Fuentes.Select(f => new SelectListItem
                    {
                        Value = f.Id.ToString(),
                        Text = f.Fuente1
                    }).ToList(),
                    Estatus = _context.Estatuses.Select(e => new SelectListItem
                    {
                        Value = e.Id.ToString(),
                        Text = e.Estatus1
                    }).ToList(),
                    Posiciones = _context.Posicions.Select(p => new SelectListItem
                    {
                        Value = p.Id.ToString(),
                        Text = p.Posicion1
                    }).ToList(),
                    Sexos = _context.Sexos.Select(s => new SelectListItem
                    {
                        Value = s.Id.ToString(),
                        Text = s.Sexo1
                    }).ToList(),
                    Reclutadores = _context.Reclutadors.Select(r => new SelectListItem
                    {
                        Value = r.Id.ToString(),
                        Text = r.NombreCompleto
                    }).ToList()
                };

                return View("Index", vm);
            }

            // Fecha de contacto
            nuevo.FechaContacto = DateTime.Now;

            // Guardar en DB
            _context.DatosReclutamientos.Add(nuevo);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        #endregion

        #region Details (Overlay)
        [Authorize]
        [HttpGet]
        public async Task<IActionResult> DetailsPartial(int id)
        {

            var datos = await _context.DatosReclutamientos
                .Include(d => d.IdBaseNavigation)
                .Include(d => d.IdEmpresaNavigation)
                .Include(d => d.IdEstatusNavigation)
                .Include(d => d.IdFuenteNavigation)
                .Include(d => d.IdPosicionNavigation)
                .Include(d => d.IdReclutadorNavigation)
                .Include(d => d.IdSexoNavigation)
                .FirstOrDefaultAsync(x => x.Id ==id);

            if (datos == null)
                return NotFound();


            var vm = new ReclutamientoDetailsVM
            {
                Datos = datos,
                MostrarModal = true
            };

            return PartialView("_ReclutamientoDetailsPartial",vm);

        }


        #endregion


        #region Edit
        [Authorize]
        // GET: DatosReclutamientoes/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var datos = await _context.DatosReclutamientos.FindAsync(id);
            if (datos == null)
                return NotFound();

            var vm = new ReclutamientoIndexVM
            {
                Nuevo = datos,
                Empresas = _context.Empresas.Select(e =>
                    new SelectListItem { Value = e.Id.ToString(), Text = e.Empresa1 }),

                Bases = _context.Bases.Select(b =>
                    new SelectListItem { Value = b.Id.ToString(), Text = b.Base1 }),

                Fuentes = _context.Fuentes.Select(f =>
                    new SelectListItem { Value = f.Id.ToString(), Text = f.Fuente1 }),

                Estatus = _context.Estatuses.Select(e =>
                    new SelectListItem { Value = e.Id.ToString(), Text = e.Estatus1 }),

                Posiciones = _context.Posicions.Select(p =>
                    new SelectListItem { Value = p.Id.ToString(), Text = p.Posicion1 }),

                Sexos = _context.Sexos.Select(s =>
                    new SelectListItem { Value = s.Id.ToString(), Text = s.Sexo1 }),

                Reclutadores = _context.Reclutadors.Select(r =>
                    new SelectListItem { Value = r.Id.ToString(), Text = r.NombreCompleto })
            };




            return PartialView("_ReclutamientoEditPartial", vm);
        }


        #endregion


        #region EditPost
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind(Prefix = "Nuevo")] DatosReclutamiento model)
        {
            if (!ModelState.IsValid)
            {
                var vm = new ReclutamientoIndexVM
                {
                    Nuevo = model,
                    MostrarModal = true,

Views/DatosReclutamientoes/Delete.cshtml
@model RecursosHumanos.Models.DatosReclutamiento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DatosReclutamiento</h4>
    <hr />
    <dl class="row">
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comentarios)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comentarios)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCreación)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaCreación)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdBaseNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdBaseNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpresaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpresaNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEstatusNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEstatusNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdFuenteNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdFuenteNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPosicionNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPosicionNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdReclutadorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdReclutadorNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdSexoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdSexoNavigation.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/DatosReclutamientoes/Details.cshtml
@model RecursosHumanos.Models.DatosReclutamiento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>DatosReclutamiento</h4>
    <hr />
    <dl class="row">
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreCompleto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreCompleto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comentarios)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comentarios)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaCreación)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaCreación)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdBaseNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdBaseNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEmpresaNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEmpresaNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdEstatusNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdEstatusNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdFuenteNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdFuenteNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdPosicionNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdPosicionNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdReclutadorNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdReclutadorNavigation.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdSexoNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdSexoNavigation.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Views/DatosReclutamientoes/Edit.cshtml
@model RecursosHumanos.Models.DatosReclutamiento

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>DatosReclutamiento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            
            <div class="form-group">
                <label asp-for="NombreCompleto" class="control-label"></label>
                <input asp-for="NombreCompleto" class="form-control" />
                <span asp-validation-for="NombreCompleto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefono" class="control-label"></label>
                <input asp-for="Telefono" class="form-control" />
                <span asp-validation-for="Telefono" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comentarios" class="control-label"></label>
                <input asp-for="Comentarios" class="form-control" />
                <span asp-validation-for="Comentarios" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaCreación" class="control-label"></label>
                <input asp-for="FechaCreación" class="form-control" />
                <span asp-validation-for="FechaCreación" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEmpresa" class="control-label"></label>
                <select asp-for="IdEmpresa" class="form-control" asp-items="ViewBag.IdEmpresa"></select>
                <span asp-validation-for="IdEmpresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdBase" class="control-label"></label>
                <select asp-for="IdBase" class="form-control" asp-items="ViewBag.IdBase"></select>
                <span asp-validation-for="IdBase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdFuente" class="control-label"></label>
                <select asp-for="IdFuente" class="form-control" asp-items="ViewBag.IdFuente"></select>
                <span asp-validation-for="IdFuente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdEstatus" class="control-label"></label>
                <select asp-for="IdEstatus" class="form-control" asp-items="ViewBag.IdEstatus"></select>
                <span asp-validation-for="IdEstatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdPosicion" class="control-label"></label>
                <select asp-for="IdPosicion" class="form-control" asp-items="ViewBag.IdPosicion"></select>
                <span asp-validation-for="IdPosicion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdSexo" class="control-label"></label>
                <select asp-for="IdSexo" class="form-control" asp-items="ViewBag.IdSexo"></select>
                <span asp-validation-for="IdSexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdReclutador" class="control-label"></label>
                <select asp-for="IdReclutador" class="form-control" asp-items="ViewBag.IdReclutador"></select>
                <span asp-validation-for="IdReclutador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Views/DatosReclutamientoes/_ReclutamientoCrearPartial.cshtml
@model RecursosHumanos.Models.ViewModels.Reclutamiento.ReclutamientoIndexVM

<div class="reclutamiento-overlay"
     id="reclutamientoOverlay"
     style="display:@(Model.MostrarModal ? "flex" : "none")">

    <div class="reclutamiento-modal">

        <div class="modal-header">
            <h5><i class="bi bi-person-plus"></i> Nuevo candidato</h5>
            <button type="button" class="btn-close" onclick="ReclutamientoOverlayCreate.close()"></button>
        </div>

        <form asp-action="Create" asp-controller="DatosReclutamientoes" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-2"></div>

            <div class="row g-3">
                <div class="col-md-12">
                    <label asp-for="Nuevo.NombreCompleto"></label>
                    <input asp-for="Nuevo.NombreCompleto" class="form-control" />
                    <span asp-validation-for="Nuevo.NombreCompleto" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Nuevo.Telefono"></label>
                    <input asp-for="Nuevo.Telefono" class="form-control" />
                    <span asp-validation-for="Nuevo.Telefono" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Empresas"></label>
                    <select asp-for="Nuevo.IdEmpresa" asp-items="Model.Empresas" class="form-select"></select>
                    <span asp-validation-for="Nuevo.IdEmpresa" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Bases"></label>
                    <select asp-for="Nuevo.IdBase" asp-items="Model.Bases" class="form-select"></select>
                    <span asp-validation-for="Nuevo.IdBase" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Fuentes"></label>
                    <select asp-for="Nuevo.IdFuente" asp-items="Model.Fuentes" class="form-select"></select>
                    <span asp-validation-for="Nuevo.IdFuente" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Estatus"></label>
                    <select asp-for="Nuevo.IdEstatus" asp-items="Model.Estatus" class="form-select"></select>
                    <span asp-validation-for="Nuevo.IdEstatus" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Posiciones"></label>
                    <select asp-for="Nuevo.IdPosicion" asp-items="Model.Posiciones" class="form-select"></select>
                    <span asp-validation-for="Nuevo.IdPosicion" class="text-danger"></span>
                </div>

                <div class="col-md-6">
                    <label asp-for="Sexos"></label>
                    <select asp-for="Nuevo.IdSexo" asp-items="Model.Sexos" class="form-select"></select>
                    <span asp-validation-for="Nuevo.IdSexo" class="text-danger"></span>
                </div>

                <div class="col-md-12">
                    <label asp-for="Reclutadores"></label>
                    <select asp-for="Nuevo.IdReclutador" asp-items="Model.Reclutadores" class="form-select"></select>
                    <span asp-validation-for="Nuevo.IdReclutador" class="text-danger"></span>
                </div>

                <div class="col-md-12">
                    <label asp-for="Nuevo.Comentarios"></label>
                    <textarea asp-for="Nuevo.Comentarios" class="form-control"></textarea>
                    <span asp-validation-for="Nuevo.Comentarios" class="text-danger"></span>
                </div>
            </div>

            <div class="modal-footer mt-4">
                <button type="button" class="btn btn-secondary" onclick="ReclutamientoOverlayCreate.close()">
                    Cancelar
                </button>
                <button type="submit" class="btn btn-success">Guardar</button>
            </div>
        </form>
    </div>
</div>

Views/DatosReclutamientoes/_ReclutamientoEditPartial.cshtml
@model RecursosHumanos.Models.ViewModels.Reclutamiento.ReclutamientoIndexVM
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

<div class="reclutamiento-overlay show"
     id="reclutamientoOverlayEdit"
     style="display:@(Model.MostrarModal ? "flex" : "none")">
     
    <div class="reclutamiento-modal">

        <!-- HEADER -->
        <div class="modal-header">
            <h5>
                <i class="bi bi-pencil"></i> Editar candidato
            </h5>
            <button type="button"
                    class="btn-close"
                    onclick="ReclutamientoOverlayEdit.close()">
            </button>
        </div>

        <!-- FORM -->
        <form asp-action="Edit"
              asp-controller="DatosReclutamientoes"
              method="post">

            <!-- ID OCULTO -->
            <input type="hidden" asp-for="Nuevo.Id" />

            <div asp-validation-summary="ModelOnly"
                 class="text-danger mb-2">
            </div>

            <div class="row g-3">

                <!-- NOMBRE -->
                <div class="col-md-12">
                    <label asp-for="Nuevo.NombreCompleto"></label>
                    <input asp-for="Nuevo.NombreCompleto"
                           class="form-control" />
                    <span asp-validation-for="Nuevo.NombreCompleto"
                          class="text-danger"></span>
                </div>

                <!-- TELÉFONO -->
                <div class="col-md-6">
                    <label asp-for="Nuevo.Telefono"></label>
                    <input asp-for="Nuevo.Telefono"
                           class="form-control" />
                </div>

                <!-- EMPRESA -->
                <div class="col-md-6">
                    <label>Empresa</label>
                    <select asp-for="Nuevo.IdEmpresa"
                            asp-items="Model.Empresas"
                            class="form-select">
                    </select>
                </div>

                <!-- BASE -->
                <div class="col-md-6">
                    <label>Base</label>
                    <select asp-for="Nuevo.IdBase"
                            asp-items="Model.Bases"
                            class="form-select">
                    </select>
                </div>

                <!-- FUENTE -->
                <div class="col-md-6">
                    <label>Fuente</label>
                    <select asp-for="Nuevo.IdFuente"
                            asp-items="Model.Fuentes"
                            class="form-select">
                    </select>
                </div>

                <!-- ESTATUS -->
                <div class="col-md-6">
                    <label>Estatus</label>
                    <select asp-for="Nuevo.IdEstatus"
                            asp-items="Model.Estatus"
                            class="form-select">
                    </select>
                </div>

                <!-- POSICIÓN -->
                <div class="col-md-6">
                    <label>Posición</label>
                    <select asp-for="Nuevo.IdPosicion"
                            asp-items="Model.Posiciones"
                            class="form-select">
                    </select>
                </div>

                <!-- SEXO -->
                <div class="col-md-6">
                    <label>Sexo</label>
                    <select asp-for="Nuevo.IdSexo"
                            asp-items="Model.Sexos"
                            class="form-select">
                    </select>
                </div>

                <!-- RECLUTADOR -->
                <div class="col-md-12">
                    <label>Reclutador</label>
                    <select asp-for="Nuevo.IdReclutador"
                            asp-items="Model.Reclutadores"
                            class="form-select">
                    </select>
                </div>

                <!-- COMENTARIOS -->
                <div class="col-md-12">
                    <label asp-for="Nuevo.Comentarios"></label>
                    <textarea asp-for="Nuevo.Comentarios"
                              class="form-control">
                    </textarea>
                </div>

            </div>

            <!-- FOOTER -->
            <!-- 
            <div class="modal-footer mt-4">
                <button type="button"
                        class="btn btn-secondary"
                        onclick="ReclutamientoOverlay.close()">
                    Cancelar
                </button>

                <button type="submit"
                        class="btn btn-primary">
                    Guardar cambios
                </button>
            </div>
            -->

            <div class="modal-footer mt-4">
                <button type="button" class="btn btn-secondary" onclick="ReclutamientoOverlayEdit.close()">
                    Cancelar
                </button>
                <button type="submit" class="btn btn-success">
                    Guardar
                </button>
            </div>
        </form>

    </div>
</div>